INFO:app:Database tables created successfully
DEBUG:asyncio:Using selector: EpollSelector
 * Serving Flask app 'app'
INFO:__main__:Flask server started in background thread
 * Debug mode: on
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.31.196.16:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:__main__:Starting Telegram bot...
DEBUG:telegram.ext.ExtBot:Calling Bot API endpoint `getMe` with parameters `{}`
DEBUG:httpcore.connection:connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7f1daa35c910>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x7f1daa6f0170> server_hostname='api.telegram.org' timeout=5.0
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7f1daa6d7f50>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
ERROR:app:404 error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:172.31.196.16 - - [11/Dec/2024 00:04:14] "GET / HTTP/1.1" 404 -
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Server', b'nginx/1.18.0'), (b'Date', b'Wed, 11 Dec 2024 00:04:14 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'260'), (b'Connection', b'keep-alive'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'Access-Control-Allow-Origin', b'*'), (b'Access-Control-Allow-Methods', b'GET, POST, OPTIONS'), (b'Access-Control-Expose-Headers', b'Content-Length,Content-Type,Date,Server,Connection')])
INFO:httpx:HTTP Request: POST https://api.telegram.org/bot7675581690:AAGsAtTy06-yKG4_9jCRHTOgqeh2EHAMnwI/getMe "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:telegram.ext.ExtBot:Call to Bot API endpoint `getMe` finished with return value `{'id': 7675581690, 'is_bot': True, 'first_name': 'Builderberg Bot', 'username': 'builderberg_bot', 'can_join_groups': True, 'can_read_all_group_messages': False, 'supports_inline_queries': False, 'can_connect_to_business': False, 'has_main_web_app': False}`
DEBUG:telegram.ext.ExtBot:This Bot is already initialized.
INFO:telegram.ext.Application:Application started
INFO:__main__:Telegram bot started successfully!
ERROR:__main__:Error in Telegram bot: This event loop is already running
ERROR:__main__:Error in main: This event loop is already running
INFO:__main__:Shutting down application...
ERROR:__main__:Fatal error: This event loop is already running